// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzwN51BqLOjvCp0zyekmnuPWqfjVmcqVY',
    appId: '1:405655643611:web:788c4f7092c53821b873fe',
    messagingSenderId: '405655643611',
    projectId: 'fahm-dictionary',
    authDomain: 'fahm-dictionary.firebaseapp.com',
    storageBucket: 'fahm-dictionary.firebasestorage.app',
    measurementId: 'G-DCCFZF3ETP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi7ROjD11IAhji6TZyWUz9pXZX_b-hzao',
    appId: '1:405655643611:android:d5576d86f00ac5b2b873fe',
    messagingSenderId: '405655643611',
    projectId: 'fahm-dictionary',
    storageBucket: 'fahm-dictionary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7hDbKylaELlyzsWcrlClfGGf-VO7wZS8',
    appId: '1:405655643611:ios:87dadbca463bc47db873fe',
    messagingSenderId: '405655643611',
    projectId: 'fahm-dictionary',
    storageBucket: 'fahm-dictionary.firebasestorage.app',
    iosBundleId: 'com.example.gpDictionary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7hDbKylaELlyzsWcrlClfGGf-VO7wZS8',
    appId: '1:405655643611:ios:87dadbca463bc47db873fe',
    messagingSenderId: '405655643611',
    projectId: 'fahm-dictionary',
    storageBucket: 'fahm-dictionary.firebasestorage.app',
    iosBundleId: 'com.example.gpDictionary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzwN51BqLOjvCp0zyekmnuPWqfjVmcqVY',
    appId: '1:405655643611:web:e089e9273eff5fcfb873fe',
    messagingSenderId: '405655643611',
    projectId: 'fahm-dictionary',
    authDomain: 'fahm-dictionary.firebaseapp.com',
    storageBucket: 'fahm-dictionary.firebasestorage.app',
    measurementId: 'G-RJS91N55G3',
  );
}
